import "styles/globals.css"
import { Inter } from "next/font/google"
import { ReactNode } from "react"
import TanstackQueryProvider from "@/library/react-query-utils/TanstackQueryProvider"

const customFont = Inter({ subsets: ["latin"], variable: "--custom-font" })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className={`${customFont.variable} font-sans`}>
      <body>
        <TanstackQueryProvider>{children}</TanstackQueryProvider>
      </body>
    </html>
  )
}
